name: dbt-ci

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt-databricks
        run: pip install dbt-databricks

      - name: Generate CI profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "atliq_gold:
            target: ci
            outputs:
              ci:
                type: databricks
                catalog: atliq
                schema: ci
                host: \"$DATABRICKS_HOST\"
                http_path: \"$DATABRICKS_HTTP_PATH\"
                token: \"$DATABRICKS_TOKEN\"
                threads: 4" > ~/.dbt/profiles.yml

      - name: Install dependencies & Build dbt models in CI schema
        run: |
          dbt deps
          dbt build --target ci